User-friendly (ish) interface for metadata extraction
mrc-ide/orderly2 pull request #39
Opened 2023-07-17 18:08 UTC by richfitz

This has been requested in a few guises over the years, and I think it will perhaps form the basis of other tooling too.

Extract some fields from the metadata of a bunch of packets. The implementation is fairly rich, and is described in some detail in the docs (which I used to sketch out the interface before implementation).  I think this strikes a reasonable balance of usability, generalisability and extensibility, but very open to suggestions.

The query syntax is deliberately not-very R-ish as we might want to adopt this into the rust tool in some guise?

2023-07-19 13:52 UTC, r-ash requested changes
Some small suggested changes but looks good.

Guess big question I'm interested in is why you wanted the type conversion to be explicit instead of leaving it up to R to convert (which generally works fairly well). Just thinking ahead to other language implementations of this where the automatic conversion might not be possible or the same?

2023-07-19 13:57 UTC, richfitz commented
> Guess big question I'm interested in is why you wanted the type conversion to be explicit instead of leaving it up to R to convert (which generally works fairly well). Just thinking ahead to other language implementations of this where the automatic conversion might not be possible or the same?

I don't think this works well in practice (thinking here of why we avoid `sapply` in general). In general very little of this is knowable and we'll need the user to guide us. Trying to be chill about it will mean that different calls will result in different classes (for example, pulling `parameters` might be a character vector in one case because there's only one type of parameter and its character, a list in others and a list of lists in another). This way, the same call will be type stable even when the underlying  data changes

2023-07-19 13:59 UTC, richfitz commented on R/outpack_tools.R
> +##' as a character vector column.
currently, yes it errored. I wondered about being nice and just skipping over it but decided that every time I try and be helpful it creates complicated things to maintain later, so just threw instead. We can always walk that back later

2023-07-19 14:03 UTC, richfitz commented on R/outpack_tools.R
> +    value_i <- lapply(meta, function(x) x[[from_i]])
this did remind me though that I wanted to prevent the opaque error you get when this fails

2023-07-20 08:15 UTC, r-ash approved these changes

2023-07-20 08:32 UTC, merged