Explicitly pass environment to context
mrc-ide/orderly2 pull request #68
Opened 2023-08-02 10:08 UTC by richfitz

This simplifies some weird code, and will be more reliable in practice I think

2023-08-03 12:47 UTC, r-ash requested changes

2023-08-03 12:47 UTC, r-ash commented on tests/testthat/test-run.R
> +test_that("can ruin orderly with parameters, without orderly, globally", {
```suggestion
test_that("can run orderly with parameters, without orderly, globally", {
```

"can ruin orderly" :laughing:

2023-08-03 12:47 UTC, r-ash commented on tests/testthat/test-run.R
> +test_that("can ruin orderly with parameters, without orderly, globally", {
Actually what does "without orderly" mean here?

2023-08-03 14:22 UTC, richfitz commented on tests/testthat/test-run.R
> +test_that("can ruin orderly with parameters, without orderly, globally", {
means without orderly_run (i.e., interactively)

2023-08-07 09:38 UTC, r-ash approved these changes

2023-08-07 09:38 UTC, merged